VIA_ENABLE = yes
VIAL_ENABLE = yes
VIAL_INSECURE = no
LTO_ENABLE = yes
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
CONSOLE_ENABLE = no #Use for debugging
QMK_SETTINGS = no
# MOUSEKEY_ENABLE         = yes # Mouse keys
# EXTRAKEY_ENABLE         = yes # Audio control and System control
