CONSOLE_ENABLE = yes
POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = analog_joystick
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
VIA_ENABLE          = yes
VIAL_ENABLE         = yes
RGBLIGHT_ENABLE     = yes
RGB_MATRIX_ENABLE   = no # Can't have RGBLIGHT and RGB_MATRIX at the same time.
COMBO_ENABLE        = no
QMK_SETTINGS        = no