OLED_ENABLE = yes
OLED_DRIVER = SSD1306
EXTRAKEY_ENABLE = yes

WPM_ENABLE = yes

VIA_ENABLE = yes
VIAL_ENABLE = yes
LTO_ENABLE = yes
QMK_SETTINGS = no
TAP_DANCE_ENABLE = no
COMBO_ENABLE = no
KEY_OVERRIDE_ENABLE = no
